### ISSUE TITLE
forward slashes in url no longer being escaped with backslash in base64 encoded json data

### ISSUE THREAD

**Issue by JoeSocketLabs** [carbon/Acme#3]
Notice how the current version does not escape forward slashes, but the former version did. These are examples are from a challenge completion request.

Json Now (causes ACME error responses):
```
{
	"alg":"RS256",
	"nonce":"IqPuvK3pXdTdItWzZ-s30g",
	"url":"https://acme.local:14000/chalZ/LIYSstZRek34ZrR_BVoB4YXPaHaRX-By7W6ntjApIis",
	"kid":"https://acme.local:14000/my-account/1"
}
```

Json Previously - My fork generated json with characters escaped like so. No issues here:

```
{
	"alg":"RS256",
	"nonce":"PLDMPKgpoakyYkDNIyI6Ng",
	"url":"https:\/\/acme.local:14000\/chalZ\/bWlSLu0vwxKHVlp1M2VqjNPuhxhXpBZ1zFfyJ1vB-SQ",
	"kid":"https:\/\/acme.local:14000\/my-account\/1"
}

```

**Comment by iamcarbon** [comment]
Hi @JoeSocketLabs 

I believe this was related to removing the body instead of posting an empty {}.

This should have been fixed with:

https://github.com/carbon/Acme/commit/8396761d84faff06cba4698a09a29c632f6473c1

Let me know.
